### ISSUE TITLE
MapBox images

### ISSUE THREAD

**Issue by ch3ck** [silicon-mountain/github-users-africa#3]
Hi @prestb Any updates on this? You've been silent. We need to publish this ASAP.

**Comment by ch3ck** [comment]
@collinsnji Have you finished cleaning up the `MD` and sorting the users according to number of repositories?

**Comment by collinsnji** [comment]
@Ch3ck Yep :) https://collinsnji.github.io/github-users-africa/userdata.
But I think it's kinda slow due to the images loading. Can I open a new issue to implement a service worker to fix this?

**Comment by ch3ck** [comment]
@collinsnji Yes you can.

**Comment by collinsnji** [comment]
I fixed the issue by sorting the `JSON` dump before uploading. It wasn't the photos causing the slow loading, it was the client side sorting :). Check it out [here](https://collinsnji.github.io/GitHub-Cameroon/users)
