### ISSUE TITLE
Having a 404 not found

### ISSUE THREAD

**Issue by Sanix-Darker** [silicon-mountain/github-users-africa#8]
When trying to access: https://github.com/silicon-mountain/github-cm/

**Comment by AchoArnold** [comment]
If you're having a 404 error then perhaps that's a problem from GitHub. I just opened the link on my local computer and it worked perfectly

![screenshot 2018-11-22 13 10 36](https://user-images.githubusercontent.com/4196457/48902171-0698a580-ee58-11e8-861f-c6b5efc3b93e.png)

**Comment by Sanix-Darker** [comment]
if it's working locally, maybe send it on *Heroku* ? 
Because anyone clicking the link will think the app is not working Well, because it's broken!

**Comment by AchoArnold** [comment]
@Sanix-Darker  not sure I understand what you mean. Which link isn't working?
